---
- hosts: all
  become: yes

  vars_files:
    - drone_config.yaml
  vars:
    CAPACITY: "4"
    RUNNER_NAME: "VM"

  tasks:

    - name: apt update
      changed_when: false
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: "safe"

    - name: Install docker
      apt:
        name: "docker.io"
        state: present

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install docker python package
      pip:
        name: docker

    - name: Start drone runner
      docker_container:
        name: runner 
        image: drone/drone-runner-docker:1
        restart_policy: always
        ports:
        - "3000:3000"
        env:
          DRONE_RPC_PROTO: "https" 
          DRONE_RPC_HOST: "{{ DRONE_HOST }}"
          DRONE_RPC_SECRET: "{{ DRONE_SECRET }}"
          DRONE_RUNNER_CAPACITY: "{{ CAPACITY }}"
          DRONE_RUNNER_NAME: "{{ RUNNER_NAME }}"
        mounts:
          - source: "/var/run/docker.sock"
            target: "/var/run/docker.sock"
            type: bind
